### ISSUE TITLE
Gatsby Error 10123?

### ISSUE THREAD

**Issue by HarisNazir** [andreabac3/dsc-website-template#2]
![Screenshot 2020-09-26 at 15 22 33](https://user-images.githubusercontent.com/22562559/94342872-1c56f300-000c-11eb-85db-89b239bb7ea1.png)

**Comment by HarisNazir** [comment]
Line 33 in gatsby-config.js remove the curly bracket (or comment out)

**Comment by andreabac3** [comment]
Hello @HarisNazir, I don't understand what you are done, can you provide an explanation of that?

Thank you in advance,
Andrea Bacciu


Please check for it @ascandone :)

**Comment by HarisNazir** [comment]
Whenever you tr

**Comment by HarisNazir** [comment]
@andreabac3 Whenever you try to deploy it came up with an error. In the gatsby config file there's an extra curly bracket. I can make a fix for you?

**Comment by andreabac3** [comment]
@HarisNazir Did you try to remove this curly brace and did the compilation work?
It seems very strange to me, since the compilation is always successful and therefore I assume that the syntax is correct.

Kind regards,
Andrea Bacciu

**Comment by ascandone** [comment]
@HarisNazir Hi, the line 33 is already commented in the original repo, so there's no way it can cause a syntax error
Can you post the full gatbsy.config.js file, if you changed it?
Also, what node version are you using? Trailing commas in JSON needs es2017+

**Comment by HarisNazir** [comment]
I just saw that - I don't know why then I was getting this syntax error I had just pulled the code and tried the compilation.

**Comment by andreabac3** [comment]
Ok with @ascandone we have fix the issue,
Surfing on your profile we notice that you have forked the project from the eu dsc org instead from my profile.
We missed to merge the actual version andreabac3/dsc-website-template into the eu dsc github organization.

Now you can merge the latest version into your project.

Thank you @HarisNazir 

Please next time: tell us your setup (os, node version, ...)

**Comment by HarisNazir** [comment]
Sorry - I'm very new to this

**Comment by andreabac3** [comment]
Thank you very much for reporting this issue to us, we are happy to be of help.
It was our forgetfulness to update the mirror version in the other organization.
However, it remained difficult for us to identify the problem since you opened the issue on another repo than the one you were using.
I repeat, thank you very much for your report and have a nice day :) @HarisNazir
