### ISSUE TITLE
Images are blurred.

### ISSUE THREAD

**Issue by timothydillan** [andreabac3/dsc-website-template#3]
Hey there! First of all, thanks a lot for the template!

I have deployed my own customized DSC website using your template with Firebase Hosting. However, the images in the tech and team sections are blurred. 

Here's the link to the website: https://dsc-psba.web.app/

Here's the link to the repo: https://github.com/dsc-psba/website

Here's a video of the problem: https://streamable.com/3hbclg

I've tried:
1. Adding a quality parameter in each childImageSharp query -> quality: 100
2. Added a `loading="eager"` parameter in the <Img> statement
3. Removed cache

and yet nothing helped.

Any help is appreciated.

**Comment by andreabac3** [comment]
Hi @timothydillan , 
thank you for your appreciation!
Can you show your fork to me and @ascandone in order to better understand the code problem?

Thank you,
Andrea

**Comment by timothydillan** [comment]
> Hi @timothydillan ,
> thank you for your appreciation!
> Can you show your fork to me and @ascandone in order to better understand the code problem?
> 
> Thank you,
> Andrea

Sure! I just edited the post.

**Comment by andreabac3** [comment]
Hi @timothydillan,
we took a look at your repository, it sounds really strange that you don't work on one of our branches and this makes it difficult to understand which commit you started from.

We are unable to reproduce your problem, could you please fork the repository (from my account) and paste your .yaml and images?

Thank you very much, let us know

**Comment by timothydillan** [comment]
Hi @andreabac3,

Sorry for the late reply. I couldn't find a solution to it, so I decided to retrieve the image by making a static folder instead, and it worked fine. Closing this issue as no further discussion needed. Thanks a lot!
