### ISSUE TITLE
Buttons not working (Failed to load resource: the server responded with a status of 404 ())

### ISSUE THREAD

**Issue by emilyjonesr** [andreabac3/dsc-website-template#4]
Hi, thank you for the awesome template! Made getting my club's website up very easy, however I am running into a problem now that we have deployed it.

Using the Quick Start directions you left in the ReadMe, everything seems to work properly when hosting it locally, however after deploying it to Google Cloud Platform, I am unable to use the button in the top corner that is present on the mobile version/if you make the screen small to display the nav bar options. I added extra features to my club's website, one of which is a button, which also does not work after deployment. Looking at the Google Developer tools console, there are a bunch of "Failed to load resource: the server responded with a status of 404 ()" errors. 

![Screen Shot 2021-01-18 at 7 07 28 PM](https://user-images.githubusercontent.com/58923694/104973227-0eb1e880-59c2-11eb-80ad-f9647b0af4c9.png)

I redid the quick start directions and just deployed your code (literally today so the latest version) to be sure my code wasn't what was causing the errors. I also added console log messages to the buttons, which do not print in the console. In addition, I tried hosting on firebase to see if it was an issue with GCP, but the same issues are happening there.

I'm not sure if it's an issue with different versions of gatsby or something, but if you guys have an ideas of how to fix it that would be greatly appreciated!

Not sure it matters, but for reference, I'm on a mac, using vscode, and to deploy to GCP, I ran "npm run build" and uploaded the "public" file along with an app.yaml file.

Also just a side note, I saw someone else had issues with the images being blurry, I had the same issue. It was only after deployment and it was there when deploying the program right after following the Quick Start directions. I ended up removing any local images and used links to google drive images. Not sure why that was happening but thought I'd let you know :)

**Comment by andreabac3** [comment]
Hi Emily,
sorry for delay, we are working on your problem @ascandone .

Kind Regards,
Andrea

**Comment by emilyjonesr** [comment]
Hi!

Thank you, I've done some more digging and thought I'd update you. 

The problem still exists where I cannot use buttons on the website, such as the nav button on mobile version, however I have realized a few things.

The errors I sent before are likely a result of my app.yaml file and not your project. However, I did re-clone and deploy your project without me editing code to firebase to test if the button worked there, and you still cannot use the button and these errors appear in the console.
![Screen Shot 2021-01-26 at 1 31 12 PM](https://user-images.githubusercontent.com/58923694/105888606-2c430b80-5fdb-11eb-95ef-351ad41a1016.png)

Hope this helps and let me know if you know how to fix it. Thanks!

**Comment by ascandone** [comment]
Hi @emilyjonesr, can you link your repository? It is quite impossible to figure out the problem from just the stack traces

**Comment by emilyjonesr** [comment]
Hi! 

Sorry for the late reply. Are you unable to recreate the issue?

To simplify things, here is the website deployed directly after cloning it on firebase: https://tester-df42a.web.app/
and here is my repo https://github.com/emilyjonesr/dsctester (although it should be identical to yours because I didn't edit any code, only ran "npm run build").

You can see the errors in the google developer console, and if you try to use the mobile version of this website, the nav button does not work.

Thanks!

**Comment by emilyjonesr** [comment]
Update: I found a workaround online that stopped the errors!
I removed "gatsby-plugin-offline" from the package.json file.
Here is where I got the idea from: https://github.com/gatsbyjs/gatsby/issues/26563
